"""
Production and streaming-platform metadata for the documentary corpus.

Every film in the master list is included as-is -- no confidence-based
filtering. See production_streaming_classification.csv for the underlying
confidence/evidence columns per entry.

Note: some titles here are near-duplicates of each other (e.g. "Gunned Down"
and "Gunned Down: The Power of the NRA") because the source document listed
the same film twice under slightly different titles in two different
sections. Both point to the same classification, so this is harmless for
fuzzy matching, just worth knowing if you spot it while reviewing.

Keys are display titles from the master documentary list -- match against
results_df["documentary"] with fuzzy_match_title() in new_export_html.py,
since transcript filenames are close but not identical to these titles.
"""

PRODUCTION_TYPE = {
    'Bowling for Columbine': 'Studio/Network-backed',
    'The Brutal Truth: A Violence Documentary': 'Independent',
    'Guns and Mothers': 'Independent',
    'Inside a Gun Shot Victim': 'Independent',
    'The Interrupters': 'Independent',
    'Tough Guise 2': 'Independent',
    'Triggering Wounds': 'Independent',
    'Gunned Down': 'Studio/Network-backed',
    'When the Shooting Stops': 'Independent',
    'Living for 32': 'Independent',
    'Real Life Teens: Guns at School – How Safe Do  Teens Feel?': 'Independent',
    'Cities in Crisis: Youth Violence': 'Independent',
    'Romeo is Bleeding': 'Independent',
    'The Armor of Light': 'Studio/Network-backed',
    'Under the Gun': 'Studio/Network-backed',
    'Newtown': 'Studio/Network-backed',
    'Tower': 'Independent',
    'Gun Nation': 'Studio/Network-backed',
    '91%: A Film About Guns in America': 'Studio/Network-backed',
    'Trigger: The Ripple Effect of Gun Violence': 'Independent',
    'G is for Gun': 'Independent',
    'One October Night: A Nightmare in Las Vegas': 'Independent',
    'Whose Streets': 'Studio/Network-backed',
    'Charm City': 'Independent',
    'Song of Parkland': 'Studio/Network-backed',
    'Always in Season': 'Independent',
    'American Tragedy': 'Independent',
    'Behind The Bullet': 'Independent',
    'Come and Take It': 'Independent',
    'Club With No Name': 'Independent',
    'R.I.P. T-Shirts': 'Studio/Network-backed',
    'Freedia Got a Gun': 'Independent',
    'Bulletproof': 'Independent',
    'Us Kids': 'Studio/Network-backed',
    'The Price of Freedom': 'Studio/Network-backed',
    'When Claude Got Shot': 'Independent',
    'All These Sons': 'Studio/Network-backed',
    'Quiet Room': 'Independent',
    'Gun Shot Wound': 'Independent',
    'US Mothers Fighting Against Gun Violence': 'Studio/Network-backed',
    'Murders that Matter': 'Studio/Network-backed',
    'A Hope That Lights the Way': 'Independent',
    'Sol in the Garden': 'Independent',
    'House of Tulip': 'Independent',
    'Put the Guns Down': 'Independent',
    'Life After The Gunshot': 'Independent',
    'CHI-TOWN GUNS, GUN VIOLENCE & THE NRA': 'Independent',
    'The Takedown: American Aryans': 'Studio/Network-backed',
    'Active Shooter: America Under Fire': 'Studio/Network-backed',
    'Gun Fight': 'Studio/Network-backed',
    'Shell Shocked': 'Independent',
    'Ears, Nose and Throat': 'Independent',
    'Vanilla Cake with Strawberry Filling': 'Independent',
    'Gunned Down: The Power of the NRA': 'Studio/Network-backed',
    'Making a Killing: Guns, Greed, and the NRA': 'Independent',
    'Peace Officer': 'Independent',
    "Gabby Giffords Won't Back Down": 'Studio/Network-backed',
    '2nd Chance': 'Studio/Network-backed',
    'Parkland Rising': 'Independent',
    'Run, Hide, Fight: Growing Up Under the Gun': 'Studio/Network-backed',
    'The Perfect Neighbor': 'Independent',
    'Our Philadelphia': 'Independent',
}

STREAMING_CATEGORY = {
    'Bowling for Columbine': 'Free Streaming',
    'The Brutal Truth: A Violence Documentary': 'Buy/Rent',
    'Guns and Mothers': 'Buy/Rent',
    'Inside a Gun Shot Victim': 'Buy/Rent',
    'The Interrupters': 'Buy/Rent',
    'Tough Guise 2': 'Buy/Rent',
    'Triggering Wounds': 'Buy/Rent',
    'Gunned Down': 'Buy/Rent',
    'When the Shooting Stops': 'Buy/Rent',
    'Living for 32': 'Buy/Rent',
    'Real Life Teens: Guns at School – How Safe Do  Teens Feel?': 'Buy/Rent',
    'Cities in Crisis: Youth Violence': 'Buy/Rent',
    'Romeo is Bleeding': 'Buy/Rent',
    'The Armor of Light': 'Free Streaming',
    'Under the Gun': 'Buy/Rent',
    'Newtown': 'Buy/Rent',
    'Tower': 'Buy/Rent',
    'Gun Nation': 'Buy/Rent',
    '91%: A Film About Guns in America': 'Free Streaming',
    'Trigger: The Ripple Effect of Gun Violence': 'Free Streaming',
    'G is for Gun': 'Buy/Rent',
    'One October Night: A Nightmare in Las Vegas': 'Free Streaming',
    'Whose Streets': 'Free Streaming',
    'Charm City': 'Buy/Rent',
    'Song of Parkland': 'Major Platform',
    'Always in Season': 'Buy/Rent',
    'American Tragedy': 'Buy/Rent',
    'Behind The Bullet': 'Free Streaming',
    'Come and Take It': 'Buy/Rent',
    'Club With No Name': 'YouTube',
    'R.I.P. T-Shirts': 'Major Platform',
    'Freedia Got a Gun': 'Buy/Rent',
    'Bulletproof': 'Buy/Rent',
    'Us Kids': 'Free Streaming',
    'The Price of Freedom': 'Buy/Rent',
    'When Claude Got Shot': 'Buy/Rent',
    'All These Sons': 'Major Platform',
    'Quiet Room': 'Buy/Rent',
    'Gun Shot Wound': 'YouTube',
    'US Mothers Fighting Against Gun Violence': 'YouTube',
    'Murders that Matter': 'Buy/Rent',
    'A Hope That Lights the Way': 'Buy/Rent',
    'Sol in the Garden': 'YouTube',
    'House of Tulip': 'YouTube',
    'Put the Guns Down': 'Buy/Rent',
    'Life After The Gunshot': 'YouTube',
    'CHI-TOWN GUNS, GUN VIOLENCE & THE NRA': 'Buy/Rent',
    'The Takedown: American Aryans': 'Major Platform',
    'Active Shooter: America Under Fire': 'Major Platform',
    'Gun Fight': 'Buy/Rent',
    'Shell Shocked': 'Buy/Rent',
    'Ears, Nose and Throat': 'Buy/Rent',
    'Vanilla Cake with Strawberry Filling': 'Buy/Rent',
    'Gunned Down: The Power of the NRA': 'Buy/Rent',
    'Making a Killing: Guns, Greed, and the NRA': 'YouTube',
    'Peace Officer': 'Free Streaming',
    "Gabby Giffords Won't Back Down": 'Buy/Rent',
    '2nd Chance': 'Major Platform',
    'Parkland Rising': 'Buy/Rent',
    'Run, Hide, Fight: Growing Up Under the Gun': 'Buy/Rent',
    'The Perfect Neighbor': 'Major Platform',
    'Our Philadelphia': 'YouTube',
}